services:
  - type: web
    name: sb-scanner
    image:
      url: docker.io/wonwooseo/sb-scanner:latest
    startCommand: ./api --port $PORT
    envVars:
      - key: LOGLEVEL
        value: INFO
    autoDeploy: false
