services:
  - type: web
    name: sb-scanner
    runtime: image
    image:
      url: docker.io/antares1959/sb-scanner-web:latest
    startCommand: ./api --port $PORT
    envVars:
      - key: LOGLEVEL
        value: INFO
      - key: SECRETS
        value: /etc/secrets/secrets.yaml
    autoDeploy: false
    plan: free
    region: singapore
